# Generated by Django 4.0.5 on 2022-06-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_alter_about_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='coursework',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='experience',
            name='about',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projects',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
