# Generated by Django 4.0.5 on 2022-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_framework_project_technicalskill_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
