# Generated by Django 4.0.5 on 2022-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_about_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
