# Generated by Django 4.0.5 on 2022-06-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_alter_about_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(default=1999),
        ),
    ]
