# Generated by Django 4.0.5 on 2022-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_education_degree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.URLField(blank=True),
        ),
    ]
