# Generated by Django 4.0.5 on 2022-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0014_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
