# Generated by Django 4.0.5 on 2022-08-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0017_alter_experience_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
