# Generated by Django 4.0.4 on 2023-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0018_experience_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
