# Generated by Django 4.0.4 on 2023-02-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0019_alter_about_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='coursework',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
