# Generated by Django 4.0.4 on 2023-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0021_about_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='resume',
            new_name='javascript_resume',
        ),
        migrations.AddField(
            model_name='about',
            name='python_resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
